const SHAYARI_COLLECTION = [
  { id: "sh-1", hindi: "दिल ही तो है न संग-ओ-ख़िश्त दर्द से भर न आए क्यों, रोएँगे हम हज़ार बार कोई हमें सताए क्यों।", hinglish: "Dil hi to hai na sang-o-khisht dard se bhar na aaye kyun, roenge hum hazar baar koi humein satae kyun.", english: "It is but a heart, not a stone; why shouldn't it fill with pain?", author: "Mirza Ghalib", category: "Classic Heartbreak" },
  { id: "sh-2", hindi: "फ़ासले ऐसे भी होंगे कभी सोचा न था, सामने बैठा था मेरे और वो मेरा न था।", hinglish: "Fasle aise bhi honge kabhi socha na tha, samne baitha tha mere aur wo mera na tha.", english: "I never thought distances could be like this; they sat right across from me, yet belonged to another.", author: "Ahmad Faraz", category: "Unsaid Love" },
  { id: "sh-3", hindi: "हाथ छूटे भी तो रिश्ते नहीं छूटा करते, वक़्त की शाख़ से लम्हे नहीं टूटा करते।", hinglish: "Haath choote bhi to rishte nahi choota karte, waqt ki shaakh se lamhe nahi toota karte.", english: "Even if hands part, true bonds never loosen.", author: "Gulzar", category: "Nostalgic Romance" }
];

const SONGS_DATABASE = [
  { id: "ab-tere-bin-jee-lenge-hum", title: { en: "Ab Tere Bin Jee Lenge Hum", hi: "अब तेरे बिन जी लेंगे हम" }, film: "Aashiqui", filmHi: "आशिकी", year: 1990, singers: ["Kumar Sanu"], composer: "Nadeem-Shravan", lyricist: "Rani Malik", youtubeId: "rTatsmUgmiA", spotifyUrl: "https://open.spotify.com/search/Ab%20Tere%20Bin%20Jee%20Lenge%20Hum", ytMusicUrl: "https://music.youtube.com/search?q=Ab+Tere+Bin+Jee+Lenge+Hum", playlists: ["dard-90s", "raat-humsafar"], blurb: { en: "Defiance dressed up as heartbreak.", hi: "टूटे दिल का ग़ुरूर।" }, durationSeconds: 340 },
  { id: "chhod-aaye-hum", title: { en: "Chhod Aaye Hum Woh Galiyan", hi: "छोड़ आए हम वो गलियाँ" }, film: "Maachis", filmHi: "माचिस", year: 1996, singers: ["Hariharan", "Suresh Wadkar"], composer: "Vishal Bhardwaj", lyricist: "Gulzar", youtubeId: "70YFS4GvuQ0", spotifyUrl: "https://open.spotify.com/search/Chhod%20Aaye%20Hum%20Woh%20Galiyan", ytMusicUrl: "https://music.youtube.com/search?q=Chhod+Aaye+Hum+Woh+Galiyan", playlists: ["dard-90s", "raat-humsafar"], blurb: { en: "The quintessential anthem of heartbreak.", hi: "घर और बचपन छोड़ने का दर्द।" }, durationSeconds: 292 },
  { id: "tadap-tadap-ke", title: { en: "Tadap Tadap Ke", hi: "तड़प तड़प के इस दिल से" }, film: "Hum Dil De Chuke Sanam", filmHi: "हम दिल दे चुके सनम", year: 1999, singers: ["KK"], composer: "Ismail Darbar", lyricist: "Mehboob", youtubeId: "5-g-O8fMmsI", spotifyUrl: "https://open.spotify.com/search/Tadap%20Tadap%20Ke", ytMusicUrl: "https://music.youtube.com/search?q=Tadap+Tadap+Ke", playlists: ["dard-90s", "raat-humsafar"], blurb: { en: "KK's breakout masterpiece.", hi: "टूटे दिल की चीख।" }, durationSeconds: 398 },
  { id: "pehla-nasha", title: { en: "Pehla Nasha", hi: "पहला नशा पहला खुमार" }, film: "Jo Jeeta Wohi Sikandar", filmHi: "जो जीता वही सिकंदर", year: 1992, singers: ["Udit Narayan"], composer: "Jatin-Lalit", lyricist: "Majrooh Sultanpuri", youtubeId: "dTU6t-cT3j4", spotifyUrl: "https://open.spotify.com/search/Pehla%20Nasha", ytMusicUrl: "https://music.youtube.com/search?q=Pehla+Nasha", playlists: ["pehla-nasha", "ishq-mohabbat"], blurb: { en: "The ultimate Anthem of First Love.", hi: "पहले प्यार का तराना।" }, durationSeconds: 291 },
  { id: "channa-mereya", title: { en: "Channa Mereya", hi: "चन्ना मेरेया" }, film: "Ae Dil Hai Mushkil", filmHi: "ऐ दिल है मुश्किल", year: 2016, singers: ["Arijit Singh"], composer: "Pritam", lyricist: "Amitabh Bhattacharya", youtubeId: "bzSTpdcs-EI", spotifyUrl: "https://open.spotify.com/search/Channa%20Mereya", ytMusicUrl: "https://music.youtube.com/search?q=Channa+Mereya", playlists: ["dard-90s", "raat-humsafar"], blurb: { en: "Modern heartbreak's gold standard.", hi: "अलविदा कहने का दर्द।" }, durationSeconds: 289 },
  { id: "tujhe-dekha-to", title: { en: "Tujhe Dekha To Ye Jaana Sanam", hi: "तुझे देखा तो ये जाना सनम" }, film: "Dilwale Dulhania Le Jayenge", filmHi: "दिलवाले दुल्हनिया ले जायेंगे", year: 1995, singers: ["Kumar Sanu", "Lata Mangeshkar"], composer: "Jatin-Lalit", lyricist: "Anand Bakshi", youtubeId: "A63Cg5m_YlA", spotifyUrl: "https://open.spotify.com/search/Tujhe%20Dekha%20To", ytMusicUrl: "https://music.youtube.com/search?q=Tujhe+Dekha+To", playlists: ["pehla-nasha", "ishq-mohabbat"], blurb: { en: "Quintessential sound of Indian romance.", hi: "प्यार का कालजयी नगमा।" }, durationSeconds: 302 }
];

const PLAYLISTS_INFO = {
  "pehla-nasha": { id: "pehla-nasha", titleEn: "Pehla Nasha", titleHi: "पहला नशा", tagline: "First Love & Morning Romance", timeWindow: "06:00 – 12:00 IST", description: "The sweet magic of first love." },
  "ishq-mohabbat": { id: "ishq-mohabbat", titleEn: "Ishq & Mohabbat", titleHi: "इश्क़ और मोहब्बत", tagline: "Deep Romance & Passion", timeWindow: "12:00 – 18:00 IST", description: "Romantic duets across the afternoon." },
  "dard-90s": { id: "dard-90s", titleEn: "90s Dard-e-Dil", titleHi: "नब्बे का दर्द", tagline: "The Heartbreak Canon", timeWindow: "18:00 – 22:00 IST", description: "Broken promises and 90s cassette tearjerkers." },
  "raat-humsafar": { id: "raat-humsafar", titleEn: "Raat Ke Humsafar", titleHi: "रात के हमफ़र (2 AM)", tagline: "Sleepless Highway & Solitude", timeWindow: "22:00 – 06:00 IST", description: "For 2 AM solitude when words echo loudest." },
  "bekhudi-ghazal": { id: "bekhudi-ghazal", titleEn: "Bekhudi & Ghazal", titleHi: "बेखुदी और ग़ज़ल", tagline: "Unplugged Ghazals", timeWindow: "On Request", description: "Jagjit Singh reserved for heavy hearts." }
};
